### ISSUE TITLE
Artwork vanishes when the aspect ratio of the window is taller

### ISSUE THREAD

**Issue by julzKB** [Selbi182/SpotifyBigPicture#10]
Running on a vertical screen here and when I reformat Firefox to be vertical ( ie taller than wide, the artwork vanishes unfortunately ) . To repro, just make a "tall" firefox window . 
Awesome app though, glad you made it

**Comment by Selbi182** [comment]
Hey, thanks for your interest!

The app switches into a different mode if the aspect ratio goes below 3/2. This is simply because there isn't enough space to fit everything on the screen.

How do you intend to use this app? With the queue or just the artwork?

**Comment by julzKB** [comment]
Hey there,

Thank you for your reply, yeah basically as a name implies I'm trying to get the largest possible artwork, but on a 9x16 vertical aspect ratio . It could be artwork cover alone ( with track info ) or with the queue since there would be a lot of unused real estate top and bottom .

**Comment by Selbi182** [comment]
That sounds possible, it will take me some time though

**Comment by julzKB** [comment]
no problem, even maxing out at 3/2 aspect ratio the artwork is still larger than the deskop Spotify app ( what kind of UI design is that ??? ) . I'll fill the rest of the screen with Spotify-Tui :)

**Comment by Selbi182** [comment]
Right, I did some experimentation in vertical mode and managed to at least get it working fine when EITHER the artwork or queue is shown. Not both however, I just don't know how to do that without rewriting a whole lot of CSS.

Here's the result for these two though:

![Artwork Vertical Mode](https://i.imgur.com/yIaD9N2.png)
![Queue Vertical Mode](https://i.imgur.com/MpVrpkF.png)

Will be released with the next public release, probably sometime this weekend :)

**Comment by julzKB** [comment]
artwork only is great ! thank you :)

**Comment by Selbi182** [comment]
Hey, new release is ou, containing the portrait mode improvementst! https://github.com/Selbi182/SpotifyBigPicture/releases/tag/v0.6

**Comment by julzKB** [comment]
perfect, thank you !
