### ISSUE TITLE
Invalid redirect URI / Performance issues

### ISSUE THREAD

**Issue by lukemattle** [Selbi182/SpotifyBigPicture#11]
Upon setting this up via the instructions, after logging into spotify using the url it provides in terminal, I get this error "INVALID_CLIENT: Invalid redirect URI"
I'm running this on a Raspberry Pi 4 with Java 11

**Comment by Selbi182** [comment]
Did you set the redirect URI in the Spotify Developer Dashboard? This is what it should look like:

![grafik](https://user-images.githubusercontent.com/8850085/221012570-b5fe9017-998b-4de6-a024-85169d902858.png)

Be sure to click the green "Add" button before saving. I fell into this trap a couple of times myself.

**Comment by lukemattle** [comment]
I still get the same thing after adding that. saving it and relauching the .jar

**Comment by Selbi182** [comment]
You wrote the wrong port. It should be 8183, not 8131

**Comment by Selbi182** [comment]
More specifically, it should be the port specified in the application.properties file

**Comment by lukemattle** [comment]
oops
works now!
this is amazing by the way, love it (also vertical mode is a very nice touch)
I don't know whether this is the place for suggestions but you should add a low refresh rate option (for it to only render at like 1 or 2 FPS to make my CPU hurt a little less)

**Comment by Selbi182** [comment]
Glad to help!

To save on resources, you can try disabling transitions. It won't look as pretty, but it's what's causing the biggest CPU spikes

**Comment by Selbi182** [comment]
@lukemattle Any luck with the performance?

**Comment by lukemattle** [comment]
@Selbi182 I still get 50% idle cpu usage on my pi when I have it on but I can just access it from my pc, which is fine. One thing I did notice is that my pi's display is 1600x900, does that mess with the placement of things because things can overlap when on that screen

**Comment by Selbi182** [comment]
I don't know what else I can do to reduce CPU usage... Can you do me a favor and check how doing the following things affects the CPU usage?

* Toggle "Prerender Background" in the settings menu. It should be on at all times and is also enabled default, but I'm curious how disabling it will affect the CPU usage. (In theory, it should skyrocket.)
* Hit F12 to open the web console and add `display: none` to some elements. One by one, it should become easier on the CPU. Please report back which elements cause the biggest CPU usage (I'm suspecting it's going to be `background-rendered`)

As for the resolution, 1600x900 is still 16:9, so it shouldn't break anything... Can you send me a screenshot?

**Comment by Selbi182** [comment]
A new release is live! https://github.com/Selbi182/SpotifyBigPicture/releases/tag/v1.0 

This one has some MASSIVE performance improvements. I'd urge you to give it a try and report back :)

**Comment by Selbi182** [comment]
Closed due to silence
