### ISSUE TITLE
Cant find spotifybot.properties in the ZIP

### ISSUE THREAD

**Issue by Mid-nait** [Selbi182/SpotifyBigPicture#12]

**Comment by Selbi182** [comment]
It's right there though?

![grafik](https://user-images.githubusercontent.com/8850085/221366010-886b06df-a47f-4a12-9536-6cbe4bf3909c.png)

**Comment by Selbi182** [comment]
Still got issues with this?

**Comment by Selbi182** [comment]
I'm gonna close this due to your silence
