### ISSUE TITLE
Error after Spotify authorization.

### ISSUE THREAD

**Issue by probablypablito** [Selbi182/SpotifyBigPicture#13]
Hey! After pressing authorize I get this error.

![image](https://user-images.githubusercontent.com/55856800/221439650-44063fa0-366e-4c83-9f63-13673398b476.png)

The webapp shows up on the correct port too.

I can help debug too, I'm familiar with the Spotify API and programming as well.

**Comment by Selbi182** [comment]
Uhh, this is odd. I can't really do anything with such a generic error... Can you add me on Discord? I think that's gonna be easier than through this form: Selbi#7270

**Comment by probablypablito** [comment]
Works now for some reason!
