### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by sztoo** [Selbi182/SpotifyBigPicture#16]
Hey! Awesome work and super clean UI throughout the presets. I have a question though, do the buttons (i.e., play, volume etc.) work or do they only serve as aesthetic purposes?

**Comment by Selbi182** [comment]
It would break the original idea of the app, but it sounds doable. I'll play around with it. Thanks for your recommendation! If you got any other ideas, please share them 🙂

**Comment by Selbi182** [comment]
Good news, basic playback controls are live with the new release!

![Playback Controls](https://i.imgur.com/RBgj1Us.png)

You have to enable them in the settings menu (first option).

Please give it a try and report back! https://github.com/Selbi182/SpotifyBigPicture/releases/tag/v1.0
