### ISSUE TITLE
Interested in using, how can I get this running?

### ISSUE THREAD

**Issue by harshchobisa** [Selbi182/SpotifyBigPicture#2]
Hey!

I saw your response to the other issue on how this is pretty tough to set up. Nevertheless, I'm still pretty interested in using this. Would you mind showing how to get this running, maybe with a writeup? Would also love to connect over a call or something like that.

Thanks!

**Comment by Selbi182** [comment]
Hey there, thanks for your interest. As I've mentioned in the other post, it's really tough to set up because I really only made it for myself yet. Currently I'm a bit occupied, but I'll try to find some free time later today to give a write-up on how to set it up.

I should really make the process more straight forward...

**Comment by harshchobisa** [comment]
Hi man!

This sounds good. Please let me know if/when you can get that write-up in,
as I'd love to use this, and my friends are pretty interested too 🙂

Best,
Harsh

**Comment by Selbi182** [comment]
Hi, thanks for your patience. I've created a release with instructions on how to set this thing up. Please let me know if it worked! If there are any issues, feel free to reach out as well.

https://github.com/Selbi182/SpotifyBigPicture/releases/tag/v0.1

**Comment by harshchobisa** [comment]
Thank you! let me give this a try!

**Comment by harshchobisa** [comment]
Hey man,

Thanks so much for working on this. Unfortunately, I get stuck on step 3,
where I can't run the jar file. I'm using the following java specs:

openjdk version "14.0.1" 2020-04-14

OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)

OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)


Here's the error message:


Exception in thread "main" java.lang.reflect.InvocationTargetException

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)

at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:564)

at
org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:139)


The error message continues but I didn't want to pollute the message with
the whole message. Let me know what can be done here! Would love to get
this working, please let me know what can be done. Would love to sync over
a webex or a zoom as well.


Thanks so much for your dedication.

**Comment by Selbi182** [comment]
Damn, looks like the thinJar functionality doesn't work. I'll compile a fatJar with all dependencies inside, although it will blow up the file size from 500KB to 30MB. I'll leave another post once that's done.

**Comment by harshchobisa** [comment]
Sounds good! fatJar sounds good, I’ll look out for it.

**Comment by Selbi182** [comment]
I've updated the release. Please try again with the fat version and let me know if it works!

**Comment by harshchobisa** [comment]
Hello! I am very happy to inform you that I have the app up and working. It
looks absolutely gorgeous on my TV. Thank you so much for your effort!

**Comment by Selbi182** [comment]
I'm glad to hear that! Thanks for your interest and have fun. If you're comfortable with it, I'd be interested in a photo, as I've never seen it on another device haha

**Comment by harshchobisa** [comment]
Hey!

I'd love to. Send me an email at ***@***.*** and I can send you
a picture--github isn't letting me reply with it because it makes the
message too large :/

**Comment by Selbi182** [comment]
Looks like GitHub censored the email as well. Never mind then, it's just something I was curious about :)
