### ISSUE TITLE
no spotifybot.properties in 1.3?

### ISSUE THREAD

**Issue by 974Rider** [Selbi182/SpotifyBigPicture#20]
it looks like spotifybot.properties isn't anywhere in the 1.3 release

**Comment by Selbi182** [comment]
Oh, I'm sorry about that. But you can simply create the file yourself (same folder as the JAR file). Here's what it looks like: https://github.com/Selbi182/SpotifyDiscoveryBot/blob/master/templates/config/spotifybot.properties

**Comment by Selbi182** [comment]
Fixed the release. I accidentally uploaded the JAR, not the ZIP. Woops.
