### ISSUE TITLE
Where is the logout button?

### ISSUE THREAD

**Issue by itsjusthaif** [Selbi182/SpotifyBigPicture#25]
It would have been cool if we could have a logout prompt to allow other accounts to sign in and let the dashboard show content from that stream.

**Comment by Selbi182** [comment]
I suppose this could be done. As a workaround in the meantime, you can open the spotifybot.properties file and remove the access_token and refresh_token lines, then restart the server.

**Comment by Selbi182** [comment]
Implemented in the new release!

https://github.com/Selbi182/SpotifyBigPicture/releases/tag/v1.9
