### ISSUE TITLE
Server issues?

### ISSUE THREAD

**Issue by Ehee47** [Selbi182/SpotifyBigPicture#3]
Let me just start this by saying I have next to no experience in programming or anything of the sort. What am I doing on Github then, you might ask. I simply wanted a better fullscreen display for Spotify, and BigPicture more than delivered on that. Been using it for nearly a week now, and I'm loving it.

One thing though. Sometimes (right now included) upon startup, the page just stays blank. The clock still works, as do the other functions of the page, just that nothing comes up on display. There isn't an issue with the running of the application itself as far as I can tell, since everything seems to check out in Terminal.

Aside from this much less frequent issue, a less-pressing matter would be that after about 6-7 hours (could be more) of usage, the page gets stuck on a song once it ends. There doesn't seem to be a way (that I'm familiar with) to re-sync it to the current song, other than closing everything and waiting a few hours.

Once again, I wanna say how much I love BigPicture, and I'm really thankful you made it!

**Comment by Ehee47** [comment]
I waited a few hours and that seems to have done the trick lol. I'll keep these solutions in mind next time it happens though. Thanks a lot!

**Comment by Selbi182** [comment]
Ah cool. Yeah, just try the devices button, it does some voodoo magic in the background. If there's anything else you think could need improvement, feel free to let me know!

**Comment by Ehee47** [comment]
Sure thing! Thanks again for spicing up my background music experience while I'm doing literally anything lmao

**Comment by Ehee47** [comment]
Hey, sorry for bringing this up again. I just ran into the issue again and the devices button wasn't doing the trick so I checked the web console (which I have no experience with..) I don't think that's ideal, is it?
![Screenshot (19)](https://user-images.githubusercontent.com/119745362/207544081-321853c6-b559-4ba9-9171-a6f251567030.png)

**Comment by Selbi182** [comment]
Waiting is your best friend in these situations. From my private experience, sometimes the Spotify API simply doesn't update with the current playback information in time. I wish to know how to mitigate this, but so far I'm just as unlucky as you.

As for the Heartbeat timeouts themselves, they shouldn't be a big issue if they happen sparingly. The website keeps trying to stay connected to the Java application in the background, and sometimes that connection fails. A heartbeat is done once every 30 seconds, and if the website gets no response it reestablishes the connection. Usually, a heartbeat timeout only happens every once in a while. If it spams the console, however, that means that something is obstructing the connection between the website and the Java app.

**Comment by Ehee47** [comment]
Guess whenever it happens I just gotta wait lol. Thanks again man.
