### ISSUE TITLE
Feature request: save custom presets

### ISSUE THREAD

**Issue by Aaantoni** [Selbi182/SpotifyBigPicture#30]
I often customize and change presets depending on whether I listen to an instrumental album, or a playlist filled with songs with actual lyrics. I don't necessarily want to tweak all the settings around everytime, so it would be nice to have a "save preset" option that would somehow store the current settings.

**Comment by Selbi182** [comment]
Oh yeah, that was on my bucket list, but I wasn't sure anyone would find usefulness in such a feature. But now it's coming for sure! Thanks for the heads-up :)
