### ISSUE TITLE
Feature Request: Compatibility with Spotify DJ Feature

### ISSUE THREAD

**Issue by GupaNupa** [Selbi182/SpotifyBigPicture#32]
Add the ability to view songs being played from the DJ. Add a DJ remix button to control bar.

**Comment by Selbi182** [comment]
It doesn't seem like Spotify provides any API endpoints for the DJ feature. Plus, it's not even launched in Germany yet so I don't even really know how to use it anyway. Gotta have to close this for now, sorry. If you or I find some updates about this, this thread can be reopened.
