### ISSUE TITLE
Feature request: Linux desktop or server support

### ISSUE THREAD

**Issue by Silas-jufo** [Selbi182/SpotifyBigPicture#35]
Hello, 
i dont know if this is possible but i use Linux mainly. 
Also Linux Server support would be nice to run it on a small proxmox Server to use it on any device.

**Comment by Selbi182** [comment]
I know you already closed the ticket, so I assume you figured out on your own. However, I'm still curious: Where did the initial confusion come from? If there's something I can improve in the documentation, it'd be greatly appreciated to know :)

**Comment by Silas-jufo** [comment]
I have overlooked the docker image
