### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by ditellaluca** [Selbi182/SpotifyBigPicture#4]
Hey Mate,

I was wondering if you could create an installation process video which outlines the steps to install spotify bigpicture.
I really want to download it but have no clue what im doing and a video would greatly help.

**Comment by Selbi182** [comment]
All the steps have been written down as clear as I could. What is the part you're struggling with? :)

**Comment by Selbi182** [comment]
@ditellaluca Can I still help you? If not, I'm gonna close this ticket.

**Comment by Selbi182** [comment]
I'm going to close this due to your silence, unfortunately. Let me know if you still need help and I'll reopen this ticket.
