### ISSUE TITLE
Black Background (Suggestion)

### ISSUE THREAD

**Issue by GreenRabbits** [Selbi182/SpotifyBigPicture#6]
Is it possible to add a Black Background feature (in darker rooms or for OLED panels) ?
![image](https://user-images.githubusercontent.com/63850693/218290231-120d3902-e3b2-43d3-8403-72c78fb32e9e.png)
![image](https://user-images.githubusercontent.com/63850693/218290304-d711d5f8-9437-49dc-b1d5-c0311d4afde3.png)
I have managed to do that editing the CSS :
_#content {	background-color: black;	}_

I think it should override Background Artwork and Grain Settings, as I would just check/uncheck Black Background whenever I’m in the dark and just have the previous interface when unchecking it.

**Comment by Selbi182** [comment]
Simple enough, I'll add that :)

I'm going to simply set the background to *display: none* though, since that saves on resources.
