### ISSUE TITLE
Optional Timestamps (Suggestion)

### ISSUE THREAD

**Issue by GreenRabbits** [Selbi182/SpotifyBigPicture#7]
It would be great to add the possibility to hide both current and total timestamps which are big, because the progress bar already gives you an idea of them by its position and its speed. 
![image](https://user-images.githubusercontent.com/63850693/218290622-7984e71e-63d0-47e2-86f9-cf1308ca14df.png)
![image](https://user-images.githubusercontent.com/63850693/218290625-f84696c0-b30d-4c76-bc6b-58511f245525.png)
I have managed to do that editing the CSS :
_#bottom-right {	visibility: hidden;	}_

There may be a better way of doing it, lowering (centering vertically in the free space) the progress bar when both Playback Meta Info and Timestamps are unchecked.

**Comment by Selbi182** [comment]
Hiding the timestamps is simple enough, but vertically centering the layout is on a whole different level, unfortunately.

**Comment by Selbi182** [comment]
Implemented. Will be available in the next release :)
