### ISSUE TITLE
Vertical Mode (Suggestion)

### ISSUE THREAD

**Issue by GreenRabbits** [Selbi182/SpotifyBigPicture#8]
It would be useful to have a Vertical Mode as the one in previous Spotify’s fullscreen mode. It looks more esthetic in my opinion as the album artwork and the title don’t have the same height and width. The option could be ungreyed only when Queue and Playlist Info are disabled or it could just display the title and the bottom, Album Artwork and Queue side-by-side and Playlist Info at the top like usual.
![image](https://user-images.githubusercontent.com/63850693/218290945-21998bfe-53de-4d24-a74d-2278cd1afe6a.png)
![image](https://user-images.githubusercontent.com/63850693/218291108-35d3e449-afb7-4919-8eea-a494dd8fdf1a.png)

I've made multiple changes to the CSS:

_#content-top {	flex-direction: column;	}
#artwork {
	width: unset;
text-align: center;
margin-bottom: 2vh; 	(To create a space between Artwork and Title)
}
#artwork-img {	position: relative;     }
#info {	width: unset;	}
#top-info {	height: 0px;	}	(Otherwise the title is cropped, I didn’t find another solution)_

Here that the Spotify logo is below the Artwork instead of being at the top. I think the “info” div should be split to fix this and to make this setting compatible with Queue and Playlist Info.

**Comment by Selbi182** [comment]
How do you intent to make this compatible with Queue and Playlist Info? There really isn't any space

**Comment by Selbi182** [comment]
![grafik](https://user-images.githubusercontent.com/8850085/218324837-f0cf87f7-73e7-4dc6-9dde-4cacd6681779.png)

Vertical Mode is implemented :)

**Comment by GreenRabbits** [comment]
First of all, thank you, it really looks incredibly beautiful !
This feature might be used without Queue and Playlist Info mostly. Anyway, in order to make it compatible with Queue and Playlist Info, we could just put the Title at the top or at the bottom of Album Artwork and Queue, and put the Playlist Info at the upper-right corner. 
Here are two examples :

![image](https://user-images.githubusercontent.com/63850693/218346812-5527d887-a7b3-460f-8f63-a1dbc7f83aed.png)

![image](https://user-images.githubusercontent.com/63850693/218346830-2e371fd8-2d7f-4e73-bb47-069a2f442e8e.png)

Achieving this requires to separate the Title, Queue and Playlist info into three separate divs. , I got "center-info-main" (corresponds to Title) and "top-info" (refers to Playlist Info) out of the "info" div. It is then possible to move each one separately to their right place.
There may be a few CSS adjustments to do to arrange margins and padding.
Here are the HTML document, the different elements and what they refer to.

![image](https://user-images.githubusercontent.com/63850693/218346723-51cd73ed-310a-4ae9-adb1-2845244fc48a.png)

`<div id="top-info">` :
![image](https://user-images.githubusercontent.com/63850693/218347934-dbd4286e-1750-4acd-b4c4-43eb49dc6419.png)
`<div id="center-info-main">` :
![image](https://user-images.githubusercontent.com/63850693/218347921-fca91298-61c6-4036-bc2f-51bedd45e05f.png)
`<div id="info">` :
![image](https://user-images.githubusercontent.com/63850693/218347625-269dd16d-901b-4a35-820e-ef9b6c1a303f.png)
