### ISSUE TITLE
Optional & Resizable items (Suggestion)

### ISSUE THREAD

**Issue by GreenRabbits** [Selbi182/SpotifyBigPicture#9]
It would be great to make the Album Artwork, Title, Timestamps and maybe Progress Bar all optional in order to have one of them at a time. The resizability may be useful on smaller screens, portrait screens or from a long watching distance. We could make them bigger or smaller individually with Visual Preferences menu, or all together using the browser’s zoom tool. I think Album Artwork and Title should be centered when displayed alone, with appropriate padding.
Here are few examples :
![image](https://user-images.githubusercontent.com/63850693/218291381-be8bb51d-e0e1-4fcd-aa80-fac2d4a0fc67.png)

![image](https://user-images.githubusercontent.com/63850693/218291386-20b0e719-2cd7-4d0a-aaa4-57fdd2b2517b.png)
![image](https://user-images.githubusercontent.com/63850693/218291394-e02c58f8-666a-4d19-b414-daf8a3e56a00.png)
![image](https://user-images.githubusercontent.com/63850693/218291692-ce090718-cfef-4bca-afde-9130ca8fda0f.png)

**Comment by Selbi182** [comment]
I think this would be too complex to implement like this. Frankly, being so simplistic completely misses the inherent idea of this project. If you want it to be that simplistic, feel free to make your own modifications.

However, the second option of not displaying the artwork and making everything centered is actually pretty cool! I will implement that

**Comment by Selbi182** [comment]
Hiding the artwork has been implemented and will be shipped with the next release :)

For the other suggestions, take a look at the Stylus addon. It lets you create custom CSS modifications for individual websites: https://addons.mozilla.org/en-US/firefox/addon/styl-us/
